import { FullReviewReport } from "./types";

export interface ArticleTab {
  id: string;
  title: string;
  shortName: string;
  targetJournal?: string;
  report: FullReviewReport;
  createdAt: string;
}

export const INITIAL_SAMPLE_ARTICLES: ArticleTab[] = [
  {
    id: "tab-single-cell",
    title: "Single-cell transcriptional profiling of DLL3 activation in neuroendocrine lung carcinoma",
    shortName: "Single-cell transcriptio...",
    targetJournal: "Nature Communications",
    createdAt: "September 8, 2026",
    report: {
      mode: "full",
      id: "rev_sc_dll3",
      createdAt: "2026-09-08T10:00:00.000Z",
      title: "Single-cell transcriptional profiling of DLL3 activation in neuroendocrine lung carcinoma",
      overallScore: 74,
      targetJournal: "Nature Communications",
      executionMode: "llm_synthesized",
      summary: "This study utilizes single-cell RNA sequencing and CRISPR-Cas9 screens to identify POU2F1 as a primary transcriptional regulator of DLL3 expression in small cell lung cancer (SCLC). While the identification of the enhancer element provides mechanistic insight, validation is primarily derived from 8 organoid lines and lacks in vivo survival models under targeted DLL3 antibody-drug conjugates.",
      classification: {
        category: "academic_manuscript",
        categoryLabel: "Empirical Study in Molecular Oncology & Genomics",
        isAcademicManuscript: true,
        confidence: 0.98,
        salutation: "Dear Authors,;",
        advisoryMessage: "This manuscript presents a high-throughput single-cell functional genomics investigation. The experimental protocol is rigorous, though reviewers will scrutinize the statistical power of the organoid cohort and mechanistic claims regarding chemoresistance reversal.",
        detectedFeatures: [
          "Abstract / Summary section identified",
          "Methodology / Theoretical Model formulation identified",
          "Results / Numerical experiments identified",
          "Scholarly Bibliography / Reference citations detected",
          "Academic metadata & institutional affiliation detected",
          "Domain scientific & quantitative terminology verified",
        ],
        customGuidance: "Ensure all CRISPR screening variance estimates account for sgRNA off-target multiplicity adjustments.",
      },
      dimensions: {
        originality: {
          score: 4.2,
          label: "Originality & Novelty",
          verdict: "High Novelty",
          strengths: ["First characterization of POU2F1 binding at the distal DLL3 enhancer locus."],
          vulnerabilities: ["POU2F1 is broadly active across multiple neuroendocrine lineages."],
          source: "llm",
        },
        broad_interest: {
          score: 4.1,
          label: "Broad Scientific Interest",
          verdict: "Strong Field Relevance",
          strengths: ["Direct therapeutic implications for SCLC patients receiving tarlatamab."],
          vulnerabilities: ["Scope is confined to DLL3-high transcriptional subsets."],
          source: "llm",
        },
        claims_vs_evidence: {
          score: 3.4,
          label: "Claims vs Evidence Calibration",
          verdict: "Overclaim Hazard Flagged",
          strengths: ["Convincing chromatin immunoprecipitation at the nominated locus."],
          vulnerabilities: ["Stating POU2F1 targeting will 'rescue efficacy in all patients' exceeds organoid data."],
          source: "llm",
        },
        methodology: {
          score: 3.9,
          label: "Methodological Rigor",
          verdict: "Substantial Rigor",
          strengths: ["High-coverage single-cell transcriptomics on Illumina NovaSeq 6000."],
          vulnerabilities: ["Absence of non-targeting control replicates across organoid lines."],
          source: "llm",
        },
        clarity: {
          score: 4.3,
          label: "Clarity & Presentation",
          verdict: "Exemplary Exposition",
          strengths: ["Clear schematic workflow of CRISPR screen and organoid culture."],
          vulnerabilities: ["Figure 3 heatmap requires explicit normalized z-score scale."],
          source: "llm",
        },
        prior_work: {
          score: 3.8,
          label: "Prior Work & Contextualization",
          verdict: "Well Contextualized",
          strengths: ["Appropriately integrates foundational SCLC classification papers."],
          vulnerabilities: ["Missing recent 2024 phase 3 trial citations on bispecific engagers."],
          source: "llm",
        },
      },
      priorityIssues: [
        {
          id: "ISS-01",
          priority: "A",
          title: "Overgeneralized Clinical Reversal Claim Exceeds in Vitro Evidence",
          category: "Causal Claims",
          description: "The manuscript asserts that 'Targeting POU2F1 will rescue therapeutic efficacy in all neuroendocrine lung carcinoma patients,' but evidence is restricted to 8 patient-derived organoid cultures without in vivo pharmacokinetic or toxicological data.",
          evidenceAnchor: 'text: §Discussion "proves that targeting POU2F1 will rescue therapeutic efficacy..."',
          reviewerQuote: "The authors make an unsubstantiated leap from in vitro organoid knockdown to blanket clinical rescue claims across refractory cohorts.",
          actionableFix: "Recalibrate phrasing to 'demonstrates proof-of-concept sensitization in preclinical organoid models' and explicitly state in vivo limitations.",
          rebuttalStrategy: "Acknowledge the translational gap, reference planned animal xenograft studies, and present revised manuscript text with conservative epistemic framing.",
          source: "llm",
        },
        {
          id: "ISS-02",
          priority: "B",
          title: "Absence of Multiple Hypothesis Testing Correction for sgRNA Screen",
          category: "Statistics",
          description: "CRISPR screen significance was calculated via unadjusted Student's t-tests (p < 0.05), which guarantees inflated false discovery rates across 1,200 tested regulators.",
          evidenceAnchor: "text: §Methods \"Significance testing conducted via two-tailed unpaired Student's t-tests (p < 0.05)\"",
          reviewerQuote: "Screening 1,200 chromatin regulators without Benjamini-Hochberg FDR control invalidates top candidate enrichment rankings.",
          actionableFix: "Re-analyze screen counts with MAGeCK or EdgeR applying FDR q < 0.05 correction and report adjusted p-values in Supplementary Table S2.",
          rebuttalStrategy: "Provide the complete recalculated FDR table, demonstrating POU2F1 retains significance (q = 0.008) alongside top rank.",
          source: "llm",
        },
      ],
      reviewerPersonas: [
        {
          persona: "methods_reviewer",
          name: "Dr. Elena Rostova",
          title: "Associate Professor of Molecular Pathology",
          affiliation: "Memorial Sloan Kettering Cancer Center",
          expertise: "Functional genomics, 3D organoid models, CRISPR screening reproducibility",
          roleDescription: "Evaluates sample preparation, validation rigor, and screening controls.",
          decisionRecommendation: "Major Revision",
          keyChallenge: "Inadequate control sgRNAs in 3 of the 8 organoid lines.",
          assessment: "The single-cell RNA sequencing protocol is robust and well executed. However, the reliance on unadjusted p-values for screen hits and the small organoid sample size prevent unqualified endorsement.",
          majorCritiques: [
            "Lack of Benjamini-Hochberg multiple comparison adjustment in screening pipeline.",
            "Absence of rescue experiments with ectopic POU2F1 expression.",
            "Missing western blot quantification across biological replicates.",
          ],
          missingControlsOrAnalyses: [
            "Scrambled non-targeting sgRNA negative control sequencing.",
            "Flow cytometry quantification of cell-surface DLL3 protein.",
          ],
          mustAddressItems: [
            "Provide MAGeCK FDR-adjusted rankings for all 1,200 chromatin regulators.",
            "Moderate therapeutic overclaims in abstract and discussion.",
            "Clarify organoid passage numbers and culture conditions.",
          ],
          source: "llm",
        },
        {
          persona: "domain_expert",
          name: "Prof. Marcus Vance",
          title: "Chair of Thoracic Oncology Research",
          affiliation: "Heidelberg University Hospital",
          expertise: "Small cell lung cancer lineage plasticity and Notch/DLL3 signaling",
          roleDescription: "Audits translational relevance, target validity, and lineage fidelity.",
          decisionRecommendation: "Major Revision",
          keyChallenge: "Distinguishing DLL3 enhancer regulation from global ASCL1 lineage programs.",
          assessment: "The study makes a compelling mechanistic case for POU2F1 binding. However, ASCL1 is the dominant driver in SCLC-A, and the interaction between POU2F1 and ASCL1 at this locus requires direct co-immunoprecipitation evidence.",
          majorCritiques: [
            "Does not decouple POU2F1 from broader ASCL1 neuroendocrine master regulator activity.",
            "Clinical cohort correlation needs validation in an independent public dataset (e.g. George et al. 2015).",
          ],
          missingControlsOrAnalyses: [
            "Co-IP of ASCL1 and POU2F1.",
            "Survival stratification in George et al. SCLC RNA-seq cohort.",
          ],
          mustAddressItems: [
            "Discuss potential lineage shifts towards SCLC-Y or SCLC-P upon POU2F1 inhibition.",
            "Tone down claims of 'universal predictive biomarker'.",
          ],
          source: "llm",
        },
        {
          persona: "journal_editor",
          name: "Dr. Claire Sterling",
          title: "Senior Handling Editor, Oncology & Therapeutics",
          affiliation: "Nature Communications Editorial Office",
          expertise: "Translational cancer research, manuscript triage, editorial board oversight",
          roleDescription: "Evaluates broad scientific significance, advance over prior art, and desk-rejection hazards.",
          decisionRecommendation: "Major Revision",
          keyChallenge: "Ensuring in vivo relevance matches high-impact journal thresholds.",
          assessment: "The findings represent an interesting advance for the neuroendocrine cancer community. However, without in vivo demonstration of tumor regression or therapeutic synergy with DLL3-directed agents, the paper risks transfer to a more specialized journal.",
          majorCritiques: [
            "Advance over known Notch-DLL3 regulatory biology is currently incremental without animal models.",
            "Abstract overstates clinical readiness.",
          ],
          missingControlsOrAnalyses: [
            "Patient-derived xenograft (PDX) in vivo validation.",
          ],
          mustAddressItems: [
            "Revise title and abstract to accurately reflect preclinical organoid scope.",
            "Clarify data availability and deposit raw FASTQ files in GEO/SRA.",
          ],
          source: "llm",
        },
        {
          persona: "statistician",
          name: "Dr. Aris Thorne",
          title: "Head of Quantitative Biostatistics",
          affiliation: "Wellcome Sanger Institute",
          expertise: "High-dimensional genomics, false discovery rate estimation, power analysis",
          roleDescription: "Audits experimental design, sample size sufficiency, and statistical validity.",
          decisionRecommendation: "Major Revision",
          keyChallenge: "Multiplicity correction and non-independent organoid replicate handling.",
          assessment: "The statistical reporting requires substantial remediation. Relying on Student's t-test across 1,200 parallel hypotheses guarantees high false discovery. Furthermore, biological vs technical replicate definitions in Figure 2 are ambiguous.",
          majorCritiques: [
            "Screen p-values lack multiplicity adjustment.",
            "Fold change thresholds appear arbitrarily selected post-hoc.",
          ],
          missingControlsOrAnalyses: [
            "Benjamini-Hochberg FDR calculation.",
            "Permutation testing for genomic locus enrichment.",
          ],
          mustAddressItems: [
            "Deposit reproducible R or Python analysis pipeline scripts.",
            "Report exact p-values and confidence intervals for all comparisons.",
          ],
          source: "llm",
        },
        {
          persona: "devils_advocate",
          name: "Dr. Ronald Kane",
          title: "Senior Investigator & Peer-Review Critic",
          affiliation: "Karolinska Institute",
          expertise: "Adversarial stress-testing, reproducibility auditing, alternative hypothesis testing",
          roleDescription: "Probes alternative causal mechanisms, rival explanations, and boundary failure modes.",
          decisionRecommendation: "Reject / Resubmit",
          keyChallenge: "Is POU2F1 merely a passenger correlate of high transcription rate?",
          assessment: "The central premise conflates correlation with essentiality. High POU2F1 levels may simply reflect general transcriptional hyperactivation in high-grade neuroendocrine tumors. Knockdown could induce non-specific cell stress rather than selective DLL3 silencing.",
          majorCritiques: [
            "Fails to rule out non-specific transcriptional repression following shRNA knockdown.",
            "No off-target validation using secondary non-overlapping sgRNAs or CRISPRi.",
          ],
          missingControlsOrAnalyses: [
            "Measurement of housekeeping gene transcription (ACTB, GAPDH) following POU2F1 knockdown.",
            "Independent rescue assay with sgRNA-resistant POU2F1 construct.",
          ],
          mustAddressItems: [
            "Demonstrate target specificity with two independent non-overlapping sgRNAs.",
            "Address rival hypothesis of non-specific translational arrest.",
          ],
          source: "llm",
        },
      ],
      citationIntegrity: {
        totalReferences: 4,
        sampledCount: 4,
        checkedCount: 4,
        coverageNote: "100% of detected references checked against CrossRef Registry and Retraction Watch database.",
        verifiedCount: 2,
        unresolvableCount: 1,
        uncheckedCount: 0,
        retractedCount: 1,
        retractionCheckAvailable: true,
        references: [
          {
            raw: "Saunders D, et al. A DLL3-targeted antibody-drug conjugate for small cell lung cancer. Sci Transl Med. 2015. DOI: 10.1126/scitranslmed.aac9459",
            doi: "10.1126/scitranslmed.aac9459",
            title: "A DLL3-targeted antibody-drug conjugate for small cell lung cancer",
            authors: ["Saunders D"],
            status: "valid",
            isRetracted: false,
            resolutionMethod: "doi",
          },
          {
            raw: "Rudin CM, et al. Molecular subtypes of small cell lung cancer: a synthesis of biology and therapeutics. Nat Rev Cancer. 2019. DOI: 10.1038/s41568-019-0133-9",
            doi: "10.1038/s41568-019-0133-9",
            title: "Molecular subtypes of small cell lung cancer: a synthesis of biology and therapeutics",
            authors: ["Rudin CM"],
            status: "valid",
            isRetracted: false,
            resolutionMethod: "doi",
          },
          {
            raw: "Fake A, Hallucinated B. AI generated non-existent reference. J Cancer. 2024. DOI: 10.1038/s41586-999-fake01",
            doi: "10.1038/s41586-999-fake01",
            status: "unresolvable",
            isRetracted: false,
            resolutionMethod: "doi",
          },
          {
            raw: "Wakefield AJ, et al. Ileal-lymphoid-nodular hyperplasia and pervasive developmental disorder in children. Lancet. 1998. DOI: 10.1016/S0140-6736(97)11096-0",
            doi: "10.1016/S0140-6736(97)11096-0",
            title: "RETRACTED: Ileal-lymphoid-nodular hyperplasia and pervasive developmental disorder in children",
            status: "retracted",
            isRetracted: true,
            retractionDetails: "Retracted by The Lancet in Feb 2010 following GMC fitness to practise findings.",
            resolutionMethod: "doi",
          },
        ],
      },
      reportingGuideline: {
        guidelineName: "ARRIVE 2.0 (Preclinical In Vitro / In Vivo Standards)",
        standardType: "Preclinical Laboratory Research",
        scorePercent: 78,
        compliantItems: [
          'Item 1 (Study Design): Evidenced — "Patient-derived neuroendocrine organoids (n=8) were maintained in 3D Matrigel culture."',
          'Item 2 (Sample Size): Evidenced — "Patient-derived neuroendocrine organoids (n=8)..."',
          'Item 7 (Experimental Procedures): Evidenced — "For CRISPR knockout screens, a custom sgRNA library targeting 1,200 chromatin regulators was transduced at an MOI of 0.3."',
        ],
        missingOrPartialItems: [
          "Item 3 (Inclusion and Exclusion Criteria): Absent — Criteria for establishing organoid lines from patient biopsies not explicitly documented.",
          "Item 4 (Randomization & Blinding): Absent — No documentation of blinding during single-cell sequencing library preparation or scoring.",
        ],
        additionalReviewerObservations: [
          "Explicit reporting of organoid viability criteria prior to sgRNA transduction is strongly recommended.",
        ],
      },
      journalRecommendations: [
        {
          tier: "Reach",
          journalName: "Nature Communications",
          impactFactor: 16.6,
          publisher: "Springer Nature",
          fitScore: 78,
          scopeRationale: "High novelty in nominating POU2F1 as a therapeutic enhancer driver aligns with high-impact genomics scope, but requires FDR correction and in vivo models to withstand editor review.",
          rejectionRisks: ["Lack of animal xenograft survival validation.", "Overgeneralized therapeutic rescue claims."],
          requiredRevisionsForFit: ["Tone down clinical claims.", "Include multiple comparison corrections."],
        },
        {
          tier: "Realistic",
          journalName: "Journal of Thoracic Oncology",
          impactFactor: 19.8,
          publisher: "Elsevier",
          fitScore: 88,
          scopeRationale: "Specialized thoracic oncology readership will value the focus on DLL3 and actionable SCLC biomarker biology.",
          rejectionRisks: ["Screening methodology details must be fully transparent in supplementary data."],
          requiredRevisionsForFit: ["Provide detailed organoid patient clinical histories."],
        },
        {
          tier: "Fallback",
          journalName: "Cancer Research Communications",
          impactFactor: 4.8,
          publisher: "AACR",
          fitScore: 92,
          scopeRationale: "Welcomes focused preclinical validation studies with robust molecular biology data.",
          rejectionRisks: ["Minimal risk of desk rejection."],
          requiredRevisionsForFit: ["Standard format compliance."],
        },
      ],
    },
  },
  {
    id: "tab-customs-weee",
    title: "Customs microdata as a national e-waste observatory: bottom-up WEEE quantification and the discovery of hazardous waste imports in Nepal, FY 2075/76–2082/83 Author One a,*, Author Two b, Author Three a",
    shortName: "Customs microdata as",
    targetJournal: "Journal of Material Cycles and Waste Management",
    createdAt: "September 10, 2026",
    report: {
      mode: "full",
      id: "rev_customs_weee",
      createdAt: "2026-09-10T14:30:00.000Z",
      title: "Customs microdata as a national e-waste observatory: bottom-up WEEE quantification and the discovery of hazardous waste imports in Nepal, FY 2075/76–2082/83 Author One a,*, Author Two b, Author Three a",
      overallScore: 88,
      targetJournal: "Journal of Material Cycles and Waste Management",
      executionMode: "llm_synthesized",
      summary: "The manuscript provides a robust, bottom-up WEEE inventory for Nepal, successfully leveraging 59,978 import lines to overcome the lack of national sales data. The study's strength lies in its meticulous cleaning protocol and the use of natural experiments (import restrictions and trade blockades) to validate the residence-time model. The discovery of hazardous waste imports via HS-2022 heading 8549 is a significant policy-relevant finding.",
      classification: {
        category: "academic_manuscript",
        categoryLabel: "Empirical Study in Environmental & Resource Economics",
        isAcademicManuscript: true,
        confidence: 0.99,
        salutation: "Dear Authors,;",
        advisoryMessage: "This manuscript presents a highly rigorous, data-driven approach to WEEE quantification using national customs microdata. The methodology is exceptionally transparent, particularly regarding data cleaning and uncertainty propagation.",
        detectedFeatures: [
          "Abstract / Summary section identified",
          "Methodology / Theoretical Model formulation identified",
          "Results / Numerical experiments identified",
          "Scholarly Bibliography / Reference citations detected",
          "Academic metadata & institutional affiliation detected",
          "Domain scientific & quantitative terminology verified",
        ],
        customGuidance: "The residence-time Weibull parameter estimation is sound; highlighting the trade blockade natural experiment in the abstract will maximize editorial impact.",
      },
      dimensions: {
        originality: {
          score: 4.8,
          label: "Originality & Novelty",
          verdict: "Pioneering Methodology",
          strengths: ["First bottom-up microdata quantification of electronic waste in South Asian landlocked trade context."],
          vulnerabilities: ["HS code 8549 classification is recent and provides limited historical time series."],
          source: "llm",
        },
        broad_interest: {
          score: 4.4,
          label: "Broad Scientific Interest",
          verdict: "High Policy & Academic Relevance",
          strengths: ["Relevant to Basel Convention enforcement and global e-waste monitoring initiatives."],
          vulnerabilities: ["Data context is specific to Nepal customs declarations."],
          source: "llm",
        },
        claims_vs_evidence: {
          score: 4.6,
          label: "Claims vs Evidence Calibration",
          verdict: "Well-Grounded Evidence",
          strengths: ["Careful sensitivity analysis across 59,978 line items."],
          vulnerabilities: ["Informal cross-border trade with India remains unmeasured."],
          source: "llm",
        },
        methodology: {
          score: 4.7,
          label: "Methodological Rigor",
          verdict: "Exceptional Rigor",
          strengths: ["Residence-time distribution validated against trade disruption shocks."],
          vulnerabilities: ["Weibull shape parameters are imported from regional literature benchmarks."],
          source: "llm",
        },
        clarity: {
          score: 4.5,
          label: "Clarity & Presentation",
          verdict: "Clean & Systematic",
          strengths: ["Transparent data cleaning workflow and unit conversion tables."],
          vulnerabilities: ["Figure 4 flow sankey diagram is densely packed."],
          source: "llm",
        },
        prior_work: {
          score: 4.5,
          label: "Prior Work & Contextualization",
          verdict: "Comprehensive Grounding",
          strengths: ["Exhaustive synthesis of UNU-IAS e-waste monitoring standards and Basel COP decisions."],
          vulnerabilities: ["Could expand comparison with neighboring Indian e-waste inventories."],
          source: "llm",
        },
      },
      priorityIssues: [
        {
          id: "ISS-01",
          priority: "A",
          title: "Porous Border Trade Gap Must Be Explicitly Acknowledged as Limitation",
          category: "Methodology",
          description: "While customs declarations capture formal seaborne and airborne transit via Birgunj and Tatopani, informal pedestrian and vehicular movement across the 1,770 km open border with India is unquantified.",
          evidenceAnchor: 'text: §Limitations "informal transboundary flows represent an unmonitored residual"',
          reviewerQuote: "A national inventory based strictly on formal customs declarations may underestimate small consumer electronics (smartphones, tablets) smuggled across open land borders.",
          actionableFix: "Include an explicit boundary condition box specifying the formal-market operational scope, with sensitivity estimates based on mobile telecommunications SIM activation registries.",
          rebuttalStrategy: "Highlight that customs microdata represents the definitive legal baseline, and present SIM activation comparison showing formal customs accounts for >85% of total durable imports.",
          source: "llm",
        },
        {
          id: "ISS-02",
          priority: "B",
          title: "Justify Domestic Lifespan Parameter Selection for Developing Market Context",
          category: "Statistics",
          description: "Using standard European Weibull lifespan shape parameters (α=2.8, β=5.2) without adjustment may underestimate device retention times in secondary and repair markets.",
          evidenceAnchor: "equation: Eq. 3 WEEE(t) = sum M(t-x) * L(x)",
          reviewerQuote: "Electronics in low-income economies have extended lifecycles due to informal component harvesting and repeated refurbishment.",
          actionableFix: "Provide a scenario sensitivity table showing WEEE projections when device lifespans are extended by +25% and +50% under active repair economies.",
          rebuttalStrategy: "Provide the requested scenario analysis in Section 4.2, demonstrating that while generation is shifted forward by 2-3 years, cumulative mass reaches identical equilibrium.",
          source: "llm",
        },
      ],
      reviewerPersonas: [
        {
          persona: "methods_reviewer",
          name: "Dr. Kenichi Tanaka",
          title: "Senior Scientist in Material Cycles & Industrial Ecology",
          affiliation: "National Institute for Environmental Studies (NIES), Tsukuba",
          expertise: "Material Flow Analysis (MFA), WEEE residence-time modeling, customs data harmonization",
          roleDescription: "Evaluates material flow accounting, tariff code concordance, and mass balance equations.",
          decisionRecommendation: "Minor Revision",
          keyChallenge: "Mass conversion factors for composite electronic tariff lines.",
          assessment: "The methodological formulation using customs transaction records is exceptionally clear. The authors have developed an admirable cleaning pipeline for 59,978 trade entries, providing a model for other developing nations lacking dedicated market research surveys.",
          majorCritiques: [
            "Concordance between HS-2017 and HS-2022 needs an explicit correspondence mapping table in the appendix.",
            "Weight conversion factors for unmeasured tariff lines (e.g. imports recorded only in pieces) should list uncertainty bounds.",
          ],
          missingControlsOrAnalyses: [
            "Monte Carlo uncertainty simulation for average appliance unit weights.",
          ],
          mustAddressItems: [
            "Provide HS code correspondence table in Supplementary Information.",
            "Document weight conversion assumptions clearly.",
          ],
          source: "llm",
        },
        {
          persona: "domain_expert",
          name: "Prof. Priya Nair",
          title: "Professor of Environmental Economics & Circular Economy",
          affiliation: "Indian Institute of Management Calcutta",
          expertise: "South Asian resource economics, informal waste markets, transboundary waste governance",
          roleDescription: "Evaluates regional applicability, regulatory impact, and economic policy implications.",
          decisionRecommendation: "Minor Revision",
          keyChallenge: "Accounting for informal repair economy and cross-border trade.",
          assessment: "This is a landmark empirical contribution to South Asian environmental economics. Uncovering illegal hazardous waste imports under heading 8549 provides urgent policy evidence for customs authorities.",
          majorCritiques: [
            "Contextualize findings within the regional South Asian Basel Convention compliance network.",
            "Discuss policy implications for Extended Producer Responsibility (EPR) legislation in Nepal.",
          ],
          missingControlsOrAnalyses: [
            "Comparison with Indian E-Waste Management Rules (2022) targets.",
          ],
          mustAddressItems: [
            "Add discussion on national EPR policy formulation.",
            "Acknowledge open border dynamics in study limitations.",
          ],
          source: "llm",
        },
        {
          persona: "journal_editor",
          name: "Prof. Masahiro Osako",
          title: "Executive Handling Editor",
          affiliation: "Journal of Material Cycles and Waste Management Editorial Board",
          expertise: "Solid waste management, material cycles, international environmental governance",
          roleDescription: "Assesses editorial triage, scientific significance, and alignment with journal scope.",
          decisionRecommendation: "Minor Revision",
          keyChallenge: "Positioning the manuscript's international generalizability.",
          assessment: "The manuscript fits the scope of JM&WM perfectly. It bridges empirical customs data and environmental policy with high precision. The manuscript is well positioned for acceptance following minor clarifications.",
          majorCritiques: [
            "Ensure the title clearly highlights the broader methodological contribution for developing economies.",
            "Enhance policy recommendations in the concluding section.",
          ],
          missingControlsOrAnalyses: [],
          mustAddressItems: [
            "Standardize citations to JM&WM guidelines.",
            "Confirm data availability for replication.",
          ],
          source: "llm",
        },
        {
          persona: "statistician",
          name: "Dr. Soren Lindqvist",
          title: "Quantitative Econometrician & Environmental Statistician",
          affiliation: "Stockholm Environment Institute",
          expertise: "Trade microdata analytics, time series econometrics, error propagation",
          roleDescription: "Audits data cleaning procedures, outlier detection, and parameter estimation.",
          decisionRecommendation: "Minor Revision",
          keyChallenge: "Verification of outlier truncation algorithms across trade values.",
          assessment: "The econometric handling of customs microdata is sound. Truncating extreme unit prices at the 1st and 99th percentiles prevents skew from fraudulent declarations. The statistical models are well reported.",
          majorCritiques: [
            "Report standard errors for fitted Weibull scale parameters.",
            "Provide goodness-of-fit statistics for the trade blockade natural experiment.",
          ],
          missingControlsOrAnalyses: [
            "Bootstrapped confidence intervals for annual WEEE mass generation totals.",
          ],
          mustAddressItems: [
            "Include 95% confidence intervals on Figure 2 time series.",
          ],
          source: "llm",
        },
        {
          persona: "devils_advocate",
          name: "Dr. Arthur Vance",
          title: "International Trade Law & Environmental Policy Critic",
          affiliation: "Centre for International Environmental Law, Geneva",
          expertise: "Trade enforcement, transboundary waste trafficking, treaty compliance",
          roleDescription: "Stress-tests policy assumptions and boundary definitions.",
          decisionRecommendation: "Minor Revision",
          keyChallenge: "Can customs microdata distinguish legitimate used electronics from hazardous waste?",
          assessment: "The paper makes a provocative claim regarding illegal waste imports under HS 8549. The authors must ensure their classification does not mislabel functional secondary market equipment as hazardous contraband.",
          majorCritiques: [
            "Carefully define criteria used to differentiate tested functional equipment from scrap.",
            "Ensure legal assertions under the Basel Convention reflect technical guidelines adopted at COP-15.",
          ],
          missingControlsOrAnalyses: [
            "Cross-validation with physical customs inspection sample logs.",
          ],
          mustAddressItems: [
            "Clarify functional vs non-functional distinction under HS 8549 subheadings.",
          ],
          source: "llm",
        },
      ],
      citationIntegrity: {
        totalReferences: 42,
        sampledCount: 42,
        checkedCount: 42,
        coverageNote: "100% of detected bibliography citations verified against CrossRef Registry and Retraction Watch.",
        verifiedCount: 41,
        unresolvableCount: 1,
        uncheckedCount: 0,
        retractedCount: 0,
        retractionCheckAvailable: true,
        references: [
          {
            raw: "Forti V., et al. The Global E-waste Monitor 2020: Quantities, flows, and the circular economy potential. United Nations University (UNU)/United Nations Institute for Training and Research (UNITAR). DOI: 10.18356/ed44810f-en",
            doi: "10.18356/ed44810f-en",
            title: "The Global E-waste Monitor 2020",
            authors: ["Forti V"],
            status: "valid",
            isRetracted: false,
            resolutionMethod: "doi",
          },
          {
            raw: "Wang F., et al. The collection and recovery of electrical and electronic equipment in the European Union. Waste Manage. 2013. DOI: 10.1016/j.wasman.2012.09.006",
            doi: "10.1016/j.wasman.2012.09.006",
            title: "The collection and recovery of electrical and electronic equipment in the European Union",
            authors: ["Wang F"],
            status: "valid",
            isRetracted: false,
            resolutionMethod: "doi",
          },
        ],
      },
      reportingGuideline: {
        guidelineName: "STROBE Observational Reporting Guidelines (Customs Cohort Formulation)",
        standardType: "Observational Trade & Environmental Registry Cohort",
        scorePercent: 91,
        compliantItems: [
          'Item 1 (Title and Abstract): Evidenced — "Customs microdata as a national e-waste observatory: bottom-up WEEE quantification..."',
          'Item 4 (Study Design): Evidenced — "Empirical bottom-up material flow analysis using 59,978 customs declarations."',
          'Item 5 (Setting & Time Frame): Evidenced — "Nepal national customs microdata covering fiscal years 2075/76 through 2082/83."',
          'Item 7 (Variables & Data Sources): Evidenced — "Customs transaction line items extracted from ASYCUDA World database."',
          'Item 12 (Statistical Methods): Evidenced — "Weibull residence-time distribution modeling with outlier trimming at 1st and 99th percentiles."',
        ],
        missingOrPartialItems: [
          "Item 9 (Bias & Incomplete Data): Partial — Discusses customs valuation fraud but lacks formal sensitivity bounds on tariff misdeclaration.",
        ],
        additionalReviewerObservations: [
          "Recommendation to include a formal comparison between ASYCUDA customs declarations and Central Bureau of Statistics household survey data.",
        ],
      },
      journalRecommendations: [
        {
          tier: "Reach",
          journalName: "Resources, Conservation and Recycling",
          impactFactor: 13.2,
          publisher: "Elsevier",
          fitScore: 84,
          scopeRationale: "Top-tier journal for material flow analysis and circular economy. High interest in novel microdata quantification methods.",
          rejectionRisks: ["May request global or multi-country comparative data."],
          requiredRevisionsForFit: ["Expand discussion on international trade implications."],
        },
        {
          tier: "Realistic",
          journalName: "Journal of Material Cycles and Waste Management",
          impactFactor: 3.4,
          publisher: "Springer Nature",
          fitScore: 94,
          scopeRationale: "Target journal alignment is exceptional. Directly serves the journal's focus on regional material cycles, Asian WEEE management, and sound waste governance.",
          rejectionRisks: ["Minor revisions only."],
          requiredRevisionsForFit: ["Add correspondence table for HS 2017/2022 codes."],
        },
        {
          tier: "Fallback",
          journalName: "Waste Management & Research",
          impactFactor: 2.9,
          publisher: "SAGE",
          fitScore: 96,
          scopeRationale: "Strong venue for developing economy solid waste inventories and baseline policy quantification.",
          rejectionRisks: ["Virtually zero risk of rejection."],
          requiredRevisionsForFit: ["Standard reference styling."],
        },
      ],
    },
  },
  {
    id: "tab-eprime",
    title: "e-Prime - Advances in Electrical Engineering, Electronics and Energy: Grid-Forming Inverter Control in High Renewable Penetration",
    shortName: "e-Prime - Advances",
    targetJournal: "e-Prime - Advances in Electrical Engineering",
    createdAt: "September 11, 2026",
    report: {
      mode: "full",
      id: "rev_eprime",
      createdAt: "2026-09-11T12:00:00.000Z",
      title: "e-Prime - Advances in Electrical Engineering, Electronics and Energy: Grid-Forming Inverter Control in High Renewable Penetration",
      overallScore: 82,
      targetJournal: "e-Prime - Advances in Electrical Engineering",
      executionMode: "llm_synthesized",
      summary: "The paper proposes a novel virtual synchronous machine control architecture for grid-forming converters in islanded power networks. Simulation results show 38% reduction in rate of change of frequency (RoCoF) under sudden loss of generation.",
      classification: {
        category: "academic_manuscript",
        categoryLabel: "Technical Research in Power Systems & Renewable Energy",
        isAcademicManuscript: true,
        confidence: 0.97,
        salutation: "Dear Authors,;",
        advisoryMessage: "The technical formulation and MATLAB/Simulink simulations are well grounded. Reviewers will examine hardware-in-the-loop (HIL) experimental validation.",
        detectedFeatures: [
          "Abstract / Summary section identified",
          "Methodology / Theoretical Model formulation identified",
          "Results / Numerical experiments identified",
          "Scholarly Bibliography / Reference citations detected",
        ],
        customGuidance: "Provide step-by-step controller block diagrams and parameter matrices in Supplementary Information.",
      },
      priorityIssues: [
        {
          id: "ISS-01",
          priority: "A",
          title: "Include Experimental or Hardware-in-the-Loop Validation",
          category: "Methodology",
          description: "Simulation results alone without OPAL-RT or Typhoon HIL experimental confirmation may limit publication readiness.",
          reviewerQuote: "Pure Simulink simulations without real-time controller verification are insufficient for top electrical engineering venues.",
          actionableFix: "Incorporate Typhoon HIL test bench waveforms demonstrating stable synchronization during phase-angle jump.",
          rebuttalStrategy: "Present experimental testbed measurements from the 10kW laboratory prototype in Section 5.",
          source: "llm",
        },
      ],
      reviewerPersonas: [],
      citationIntegrity: {
        totalReferences: 18,
        sampledCount: 18,
        checkedCount: 18,
        coverageNote: "100% of detected bibliography citations verified against CrossRef Registry.",
        verifiedCount: 18,
        unresolvableCount: 0,
        uncheckedCount: 0,
        retractedCount: 0,
        retractionCheckAvailable: true,
        references: [],
      },
      journalRecommendations: [
        {
          tier: "Realistic",
          journalName: "e-Prime - Advances in Electrical Engineering",
          impactFactor: 4.2,
          publisher: "Elsevier",
          fitScore: 91,
          scopeRationale: "Strong fit for rapid dissemination of converter control topologies and renewable integration modeling.",
          rejectionRisks: ["Minor validation requests."],
          requiredRevisionsForFit: ["Clarify simulation parameter table."],
        },
      ],
    },
  },
  {
    id: "tab-thesis",
    title: "Thesis Title Optimal Dispatch of Multi-Energy Microgrids Considering Carbon Emission Constraints and Green Hydrogen Storage",
    shortName: "Thesis Title Optimal",
    targetJournal: "Applied Energy",
    createdAt: "September 11, 2026",
    report: {
      mode: "full",
      id: "rev_thesis_dispatch",
      createdAt: "2026-09-11T16:00:00.000Z",
      title: "Thesis Title Optimal Dispatch of Multi-Energy Microgrids Considering Carbon Emission Constraints and Green Hydrogen Storage",
      overallScore: 85,
      targetJournal: "Applied Energy",
      executionMode: "llm_synthesized",
      summary: "This work formulates a mixed-integer linear programming (MILP) model for optimal multi-energy microgrid dispatch with electrolyzer hydrogen buffering and carbon tax optimization. Evaluated across 8760 hourly dispatch steps.",
      classification: {
        category: "academic_manuscript",
        categoryLabel: "Optimization & Operations Research in Energy Economics",
        isAcademicManuscript: true,
        confidence: 0.98,
        salutation: "Dear Author,;",
        advisoryMessage: "The mathematical optimization formulation is clean and linear. Reviewers will focus on computational solve times under stochastic weather uncertainty.",
        detectedFeatures: [
          "Abstract / Summary section identified",
          "Methodology / Theoretical Model formulation identified",
          "Results / Numerical experiments identified",
          "Scholarly Bibliography / Reference citations detected",
        ],
        customGuidance: "Highlighting solver execution time across solvers (Gurobi vs CPLEX) will provide practical value.",
      },
      priorityIssues: [
        {
          id: "ISS-01",
          priority: "B",
          title: "Assess Stochastic Renewable Uncertainty via Robust Optimization",
          category: "Statistics",
          description: "Deterministic 8760-hour dispatch assumes perfect solar and wind forecast. A two-stage stochastic or robust formulation is required.",
          reviewerQuote: "The deterministic optimization ignores forecast error, yielding overly optimistic operational cost reductions.",
          actionableFix: "Implement a 10-scenario stochastic optimization or robust boundary formulation.",
          rebuttalStrategy: "Add Monte Carlo uncertainty scenario comparison demonstrating robustness within ±15% forecast error.",
          source: "llm",
        },
      ],
      reviewerPersonas: [],
      citationIntegrity: {
        totalReferences: 24,
        sampledCount: 24,
        checkedCount: 24,
        coverageNote: "100% of references verified.",
        verifiedCount: 24,
        unresolvableCount: 0,
        uncheckedCount: 0,
        retractedCount: 0,
        retractionCheckAvailable: true,
        references: [],
      },
      journalRecommendations: [
        {
          tier: "Reach",
          journalName: "Applied Energy",
          impactFactor: 11.2,
          publisher: "Elsevier",
          fitScore: 86,
          scopeRationale: "High impact venue for integrated multi-energy systems.",
          rejectionRisks: ["Demand for stochastic modeling."],
          requiredRevisionsForFit: ["Add robust formulation."],
        },
      ],
    },
  },
  {
    id: "tab-proposal",
    title: "Bishal Khatiwada PhD Research Proposal: Resource Economics and Circular Systems in Mountain Ecosystems",
    shortName: "Bishal Khatiwada Ph",
    targetJournal: "Ecological Economics",
    createdAt: "September 12, 2026",
    report: {
      mode: "full",
      id: "rev_phd_proposal",
      createdAt: "2026-09-12T09:00:00.000Z",
      title: "Bishal Khatiwada PhD Research Proposal: Resource Economics and Circular Systems in Mountain Ecosystems",
      overallScore: 89,
      targetJournal: "Ecological Economics",
      executionMode: "llm_synthesized",
      summary: "A doctoral research framework combining spatial econometric modeling with industrial ecology material flow analysis to quantify circular economy transition pathways in fragile Himalayan river basins.",
      classification: {
        category: "academic_manuscript",
        categoryLabel: "Research Framework in Ecological & Spatial Economics",
        isAcademicManuscript: true,
        confidence: 0.99,
        salutation: "Dear Candidate / Researcher,;",
        advisoryMessage: "This proposal establishes an ambitious, interdisciplinary research agenda linking transboundary trade, ecological boundaries, and localized waste management infrastructure.",
        detectedFeatures: [
          "Abstract / Summary section identified",
          "Methodology / Theoretical Model formulation identified",
          "Scholarly Bibliography / Reference citations detected",
          "Academic metadata & institutional affiliation detected",
        ],
        customGuidance: "Grounding the empirical chapters in open-source spatial datasets (Sentinel-2, OpenStreetMap) will ensure methodological feasibility.",
      },
      priorityIssues: [
        {
          id: "ISS-01",
          priority: "B",
          title: "Clarify Spatial Resolution of River Basin Material Flow Boundary",
          category: "Scope/Fit",
          description: "Defining geographic catchment boundaries in mountainous terrain requires explicit watershed elevation stratification.",
          reviewerQuote: "Define clearly whether the study boundary follows administrative district boundaries or hydrological river basin lines.",
          actionableFix: "State that primary analysis is conducted at the hydrological watershed level with administrative concordance mapping.",
          rebuttalStrategy: "Clarified in Section 2.1 with hydrological GIS boundary definitions.",
          source: "llm",
        },
      ],
      reviewerPersonas: [],
      citationIntegrity: {
        totalReferences: 35,
        sampledCount: 35,
        checkedCount: 35,
        coverageNote: "100% of references verified.",
        verifiedCount: 35,
        unresolvableCount: 0,
        uncheckedCount: 0,
        retractedCount: 0,
        retractionCheckAvailable: true,
        references: [],
      },
      journalRecommendations: [
        {
          tier: "Reach",
          journalName: "Ecological Economics",
          impactFactor: 7.0,
          publisher: "Elsevier",
          fitScore: 92,
          scopeRationale: "Leading journal for human-environment systems and ecological resource accounting.",
          rejectionRisks: ["Low."],
          requiredRevisionsForFit: ["Refine institutional policy context."],
        },
      ],
    },
  },
];
